add sleep

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,5 +35,20 @@ jobs:
           docker network create labo03-network
           docker compose up -d
 
+      - name: Attendre MySQL
+        run: |
+          sleep 10
+          timeout=60
+          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
+            echo "Waiting for MySQL..."
+            sleep 3
+            timeout=$((timeout - 3))
+            if [ $timeout -le 0 ]; then
+              echo "MySQL failed to start"
+              exit 1
+            fi
+          done
+          sleep 5
+
       - name: Run tests
         run: docker exec store_manager pytest
